### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by apan65** [Miserlou/SoundScrape#112] opened 2016-07-21 17:07 UTC
I don't know why, but download stops on this moment.
```
Track already downloaded: Timbre
Track already downloaded: Tines (SineRider Remix)
DownloadingProblem downloading Traceback (most recent call last):
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\soundscrape\soundscrape.py", line 538, in scrape_bandcamp_url
    puts(colored.green("Downloading") + colored.white(": " + track_name))
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\textui\core.py", line 68, in puts
    stream(_str)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 34, in write
    self.__convertor.write(text)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 115, in write
    self.write_and_convert(text)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 139, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 147, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\apan\appdata\local\programs\python\python35\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf3' in position 11: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\apan\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\����� �����\soundscrape.exe\__main__.py", line 9, in <module>
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\soundscrape\soundscrape.py", line 92, in main
    process_bandcamp(vargs)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\soundscrape\soundscrape.py", line 460, in process_bandcamp
    filenames = scrape_bandcamp_url(bc_url, num_tracks=vargs['num_tracks'], folders=vargs['folders'])
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\soundscrape\soundscrape.py", line 495, in scrape_bandcamp_url
    filenames.append(scrape_bandcamp_url(album_url, num_tracks, folders))
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\soundscrape\soundscrape.py", line 557, in scrape_bandcamp_url
    puts(colored.red("Problem downloading ") + colored.white(track_name))
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\textui\core.py", line 68, in puts
    stream(_str)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 34, in write
    self.__convertor.write(text)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 115, in write
    self.write_and_convert(text)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 139, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\apan\appdata\local\programs\python\python35\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 147, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\apan\appdata\local\programs\python\python35\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf3' in position 9: character maps to <undefined>
```

**Comment by Miserlou** [comment] 2016-07-21 17:14
This may actually be fixed already, did you --upgrade to latest?

**Comment by apan65** [comment] 2016-07-21 17:19
i have updated it now, but the same result.

**Comment by Miserlou** [comment] 2016-07-21 17:54
Thanks. Is this the track in question? https://soundcloud.com/archives-5/robert-farrugia-tines-sinerider-remix

**Comment by Miserlou** [comment] 2016-07-21 17:56
Doesn't happen on OSX.

**Comment by apan65** [comment] 2016-07-21 17:57
no i have been downloading full discography from bandcamp archivesdubmusic.bandcamp.com

**Comment by Miserlou** [comment] 2016-07-21 17:58
I'm gonna assume it's related to this: https://github.com/Miserlou/SoundScrape/issues/108

**Comment by apan65** [comment] 2016-07-21 18:02
is this because of ó? from https://archivesdubmusic.bandcamp.com/album/debut

**Comment by Miserlou** [comment] 2016-07-21 18:12
This may be fixed in the latest version. I can't reproduce, but I'm not on Windows so it's hard to say.

**Closed** 2016-09-04 20:52 UTC
