### ISSUE TITLE
Command python setup.py egg_info failed with error code 1

### ISSUE THREAD

**Issue by michaelg02** [Miserlou/SoundScrape#5] opened 2014-01-03 04:38 UTC
Hi I'm trying to work on your project, but I'm new to python and open source software. I'm getting this error when calling the command install soundscrape. Is this a problem with my version of pip?

the temp folder that was made to install also showed this error.
File "c:\users\michael\appdata\local\temp\pip_build_michael\mutagen\setup.py", line 37

    except EnvironmentError, err:

Thanks

**Comment by dimethylarginine** [comment] 2015-01-10 19:47
I'm converting the project to Windows and Python 3 right now, let me know if you want the source @michaelg02

**Comment by dimethylarginine** [comment] 2015-01-10 19:53
I can't fix the install, as the error is with mutagen, and the Python 3 build of mutagen is not yet on pip (to my knowledge). However, the source is working downloading files on Windows and Python 3.4.

**Comment by nomasteryoda** [comment] 2015-05-14 01:12
```
Similar issue to dimethylarginine: 
Traceback (most recent call last):                                                 
  File "<builtin>/app_main.py", line 75, in run_toplevel                           
  File "/usr/bin/soundscrape", line 5, in <module>                                 
    from pkg_resources import load_entry_point                                     
ImportError: No module named pkg_resources
```
python 3.4 on ArchLinux

**Comment by florianmski** [comment] 2015-06-03 22:07
Same thing on Arch:
Install `python2.7`, `python2-pip` and then
`sudo python2.7 /usr/bin/pip install soundscrape`
:+1:

**Comment by nomasteryoda** [comment] 2015-06-03 23:28
Ditto... Same error on my arch install.

**Comment by xHN35RQ** [comment] 2015-06-06 00:26
There is a python 3 mutagen package on pypi and it installs fine if you set the requirements correctly so that's not the problem. I think wsgiref is not python 3 so trying to install soundscrape using python 3 pip fails.

Using python 2.7 pip works fine to install all dependencies and have a working soundscrape install.

**Comment by Miserlou** [comment] 2015-06-06 04:08
Hm.. does requests work with python3? That's what needs wsgiref I think.

**Comment by xHN35RQ** [comment] 2015-06-06 22:45
`requests` does work on python3: https://pypi.python.org/pypi/requests

**Comment by xHN35RQ** [comment] 2015-06-06 23:23
ok I got soundscrape to launch under Python 3 on my fork https://github.com/xHN35RQ/SoundScrape after making some syntax changes, but it will not download files so I think there are some more changes that need to be made to port it to Python 3. I don't know how long it would take to port.

At this point I think the best option is to keep it under Python 2.7 unless there's a very compelling reason to port to Python 3, OR if it turns out it won't take that long to port.

If you choose to remain on 2.7 then maybe make a note of that in the readme that it requires 2.7 and how to install.

**Comment by Miserlou** [comment] 2015-06-07 00:28
SoundScrape on Python3 is a definite must. However, I did not realize that
requests doesn't work on python 3, that very much surprises me. Will
investigate.. or accept PRs..

**Comment by xHN35RQ** [comment] 2015-06-07 06:26
no, requests does work on python3 just fine. the requests module itself is just on 2.7.0 as of end of May.

**Comment by mobiuscoffee** [comment] 2015-07-26 23:02
Just tried installing on a recently upgraded to Xubuntu 15.04 laptop and I'm having the same issue. I think it's something with python versions, but I have no idea what to do.

Here's the error I'm getting:
```
~$ sudo pip install soundscrape
Collecting soundscrape
  Using cached soundscrape-0.16.1.tar.gz
Collecting args>=0.1.0 (from soundscrape)
  Using cached args-0.1.0.tar.gz
Collecting clint>=0.3.2 (from soundscrape)
  Using cached clint-0.4.1.tar.gz
Collecting demjson==2.2.2 (from soundscrape)
  Using cached demjson-2.2.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): fudge==1.0.3 in /usr/local/lib/python3.4/dist-packages (from soundscrape)
Collecting mutagen==1.22 (from soundscrape)
  Using cached mutagen-1.22.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-she70tqv/mutagen/setup.py", line 37
        except EnvironmentError, err:
                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-she70tqv/mutagen
```

**Comment by xHN35RQ** [comment] 2015-07-26 23:59
@mobiuscoffee try running: `pip -V` to see which version of pip you're using. If `pip` on your system is actually pip3 then you'll have troubles. You can try completely uninstalling soundscrape with `pip uninstall soundscrape` and then try re-installing forcing pip2 using `pip2 install soundscrape` remember you may need to use `sudo` when installing. Hope that helps!

**Comment by Miserlou** [comment] 2015-07-27 00:00
So what's actually happening here? I'd like to document this in the README.

**Comment by xHN35RQ** [comment] 2015-07-27 00:20
> So what's actually happening here? I'd like to document this in the README.

What's happening is that you're trying to install soundscrape via python3 which somehow has become the default on @mobiuscoffee system. Soundscrape is supposed to be installed under python2. So for 15.04 system you need to run `pip2 install soundscrape` to force the install under python2.

@Miserlou I can replicate this exact error by using `pip3 install soundscrape` which is the pip for python3. This is a problem of course since soundscrape is python2.

@mobiuscoffee your python install has defaulted to python3, and so when you run `pip` its actually running `pip3` you can verify this by going to Terminal and running `which pip` and you should see the result of `/usr/local/bin/pip` if you run `cat /usr/local/bin/pip` the first line of result will most likely be #!/usr/bin/python3. To fix see [my above comment.](https://github.com/Miserlou/SoundScrape/issues/5#issuecomment-125050403)

**Comment by mobiuscoffee** [comment] 2015-07-27 08:58
Soundscrape works now!

Running `pip -V` returns:

```
~$ pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

And `which pip` gives:
```
~$ which pip
/usr/bin/pip
```
`cat /usr/local/bin/pip returns
```
~$ cat /usr/local/bin/pip
cat: /usr/local/bin/pip: No such file or directory
```
And `cat / usr/bin/pip` returns
```
cat /usr/bin/pip
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==1.5.4','console_scripts','pip'
__requires__ = 'pip==1.5.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
    )
```
Which seems weird. I used `easy_install` to upgrade pip I think. Could that have caused more problems?

**Comment by mobiuscoffee** [comment] 2015-07-27 09:15
@xHN35RQ running `uninstall` didn't work because soundscrape never successfully installed. However, forcing `pip2` worked perfectly!

For more information here are what the other commands return for me:
```
~$ pip -V
pip 7.1.0 from /usr/local/lib/python3.4/dist-packages/pip-7.1.0-py3.4.egg (python 3.4)
```
```
~$ which pip
/usr/local/bin/pip
```
```
~$ cat /usr/local/bin/pip
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==7.1.0','console_scripts','pip'
__requires__ = 'pip==7.1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pip==7.1.0', 'console_scripts', 'pip')()
    )
```

**Comment by xHN35RQ** [comment] 2015-07-28 08:03
> running `pip uninstall soundscrape` didn't work because soundscrape never successfully installed.

Right, I guessed as much. I just wanted to make sure there wasn't a partial install before you tried installing with pip2.

And according to the results of the commands you ran, your Ubuntu is defaulting to python3. This might cause further issues in the future for python scripts that expect a python2 default environment.

In future, double check before using pip to make sure if what you're installing requires python2 and if so, use pip2 instead of just pip.

**Comment by xHN35RQ** [comment] 2015-12-08 01:11
I kind of think this was fixed? Ping @Miserlou

**Comment by Miserlou** [comment] 2015-12-08 15:39
I have no idea. 

As far as I know, this works with Python 3, assuming Mutagen is now P3 compat, which I think it is.

However, I will not confirm this until P3 support is integrated into the Travis CI testing, at which point I will mark it as P3 compatible on Pip as well. Can somebody with a fresh P3 install confirm that SC works now?

**Comment by xHN35RQ** [comment] 2015-12-08 23:06
Here's a install log that failed for me on my existing P3 install. Still need someone with a fresh P3 install to confirm if this is failing or not.

```
nick@lboih5y:~$ pip3 install soundscrape
Collecting soundscrape
  Using cached soundscrape-0.22.1.tar.gz
Collecting args>=0.1.0 (from soundscrape)
  Using cached args-0.1.0.tar.gz
Collecting clint>=0.3.2 (from soundscrape)
  Using cached clint-0.5.1.tar.gz
Collecting demjson==2.2.2 (from soundscrape)
  Using cached demjson-2.2.2.tar.gz
Collecting fudge==1.0.3 (from soundscrape)
  Using cached fudge-1.0.3.tar.gz
Collecting mutagen==1.31 (from soundscrape)
  Using cached mutagen-1.31.tar.gz
Collecting nose==1.3.7 (from soundscrape)
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 155kB 115kB/s 
Requirement already satisfied (use --upgrade to upgrade): requests[security]>=2.1.0 in ./.local/lib/python3.4/site-packages (from soundscrape)
Collecting simplejson==3.3.1 (from soundscrape)
  Using cached simplejson-3.3.1.tar.gz
Collecting soundcloud>=0.4.1 (from soundscrape)
  Downloading soundcloud-0.5.0.tar.gz
Collecting wheel==0.24.0 (from soundscrape)
  Downloading wheel-0.24.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 65kB 457kB/s 
Collecting wsgiref==0.1.2 (from soundscrape)
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-55vzqhlf/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-55vzqhlf/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-55vzqhlf/wsgiref
```

**Comment by dimethylarginine** [comment] 2015-12-09 07:38
I will try later today and I'll post the results when I can.

**Comment by xHN35RQ** [comment] 2015-12-09 08:23
Awesome. Because now it's failing on `wsgiref` (or is it setuptools? maybe I'm reading that log incorrectly) and not mutagen, which is different from the initial error posted by OP.

**Comment by dimethylarginine** [comment] 2015-12-09 13:26
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9C7UmU/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QxX7ir-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9C7UmU/cffi

**Comment by xHN35RQ** [comment] 2015-12-09 19:54
Please put three backticks above and below your block of code to help with readability. Thanks!

    ```
    if (isAwesome){
      return true
    }
    ```

**Comment by Miserlou** [comment] 2015-12-09 20:09
wsgiref in pip is not p3 compat, as it has been merged into p3 core.

Needs a requirement specifier in setup.py, ex

setup(
    ...
    install_requires=[
        'requests',
        ...
    ],
    extras_require={
        ':python_version == "2.7"': [
            'wsgiref',
        ],
    },)

how annoying

**Comment by xHN35RQ** [comment] 2015-12-09 20:13
the weird thing is that it WAS breaking on mutagen, now it's breaking on wsgiref which supposedly has p3 support??? 

Oh I see now, you have to include it differently. :disappointed: that IS annoying.

**Comment by Miserlou** [comment] 2015-12-19 20:54
Should be python3 compatible as of 0.23.0

**Comment by xHN35RQ** [comment] 2015-12-20 07:14
I can confirm it's python3 compatible and installs just fine with pip3, however I had to manually install mutagen as the soundscrape install didn't pull it in correctly.

**Comment by xHN35RQ** [comment] 2015-12-20 07:16
Everything worked fine after doing `pip3 install mutagen`

**Comment by Miserlou** [comment] 2015-12-20 18:07
Ahhhhhhhh. I know what's going on here. Shit..

The solution is even uglier than the problem. Really, we just need to have the P3 version of Mutagen in pip and all of this will go away. In my earlier tests, the current version is not compatible, and the TGZ from source control must be used.

Should be fixed in 0.23.3, I hope.

**Closed by Miserlou** 2015-12-20 18:07 UTC

**Comment by xHN35RQ** [comment] 2015-12-21 08:53
It earlier worked fine for me with pip mutagen installed via `pip3 install mutagen` - however I had to install it manually... and just now with 0.23.3 it worked nicely on Bandcamp and Soundcloud. So either way it's working great here on Python3 on 15.10. If it's at all possible it'd be nice to stick with pip only packages, and not manually pull in the TGZ but I understand if it's necessary.

**Comment by riegel** [comment] 2016-02-08 19:00
Hello,

I am getting the same error as the original poster but my system has Python 2.5.1 installed. Here is what I am getting...

` WBL  ./setup.py build
  File "./setup.py", line 40
    except EnvironmentError as err:
                             ^
SyntaxError: invalid syntax
 WBL  python
Python 2.5.1 (r251:54863, Jul 10 2008, 17:25:56) 
[GCC 4.1.2 20070925 (Red Hat 4.1.2-33)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>`

**Comment by xHN35RQ** [comment] 2016-02-09 00:22
Greg is python 3 only.

**Comment by xHN35RQ** [comment] 2016-02-09 00:23
Have you tried installing via pip2 ?

**Comment by CJJC1220** [comment] 2018-06-05 02:07
I have come across such a problem, anybody has a solution for this？thanks
C:\Users\CJJC>pip install gdsCAD
Collecting gdsCAD
  Using cached https://files.pythonhosted.org/packages/d0/54/60b48ee74d5ba364c4aaaf6a73e0d47274a501aafd3d64b04ce7b03b40f9/gdsCAD-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\setup.py", line 4, in <module>
        from git_version import sdist, get_version
      File "C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\git_version.py", line 107
        print get_version()
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\

**Comment by jaydeep-shingala** [comment] 2020-08-29 17:37
I was trying to install audiodiff packege by pip install audiodiff and getting following error. i was stuck from weeks please help...
error:
 ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-_ossu1ev\\mutagen\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-_ossu1ev\\mutagen\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-v4c_xij0'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-_ossu1ev\mutagen\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-_ossu1ev\mutagen\setup.py", line 29
        except EnvironmentError, err:
                               ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



command: pip3 install --upgrade audiodiff --user

here i am also atteching screenshot also please have a look.

![Screenshot_1](https://user-images.githubusercontent.com/69046572/91642843-3ec91100-ea4c-11ea-9a3e-2cf0036645af.png)
![Screenshot_1](https://user-images.githubusercontent.com/69046572/91642860-65874780-ea4c-11ea-82bc-8de3bafdcd8f.png)

**Comment by SimplicityGuy** [comment] 2020-09-07 18:23
Please don't file issues on other packages here. This package is the `soundscrape` repository. Renaming this issue so that it's not a prime suspect in future searches.
