### ISSUE TITLE
Problem Downloading

### ISSUE THREAD

**Issue by bukinfastard** [Miserlou/SoundScrape#198] opened 2017-09-19 01:27 UTC
Looks like this is a fairly new problem. 

<img width="391" alt="screen shot 2017-09-19 at 9 26 28 am" src="https://user-images.githubusercontent.com/32082280/30571801-a974a6c0-9d1c-11e7-8297-50925043f05a.png">

**Comment by dkeona** [comment] 2017-09-19 03:45
{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":15000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2017/09/19 20:31:32 +0000"}}]}

max 15k requests per 24hr period with the client ID. someone was just bombin the api with requests. 

good guy dev was nice enough to let everyone use his key. too bad SC is not giving out anymore keys. otherwise, could edit the client ID to your own

**Comment by jwofles** [comment] 2017-09-19 19:17
This sucks :/

**Comment by Miserlou** [comment] 2017-09-19 19:30
Boooooooo. Need a new key from SC.

**Comment by bluesodium** [comment] 2017-09-25 12:50
they aren't releasing any more new keys - any other keys available?

**Comment by Miserlou** [comment] 2017-09-25 12:57
The key is taken from the SC web player.

**Comment by Miserlou** [comment] 2017-10-07 15:59
Getting real sick of this shit

$ soundscrape https://soundcloud.com/lostdogz/snuggles-chapstick
Downloading: Snuggles - Chapstick
Problem downloading Snuggles - Chapstick

fix soon

**Comment by bsans** [comment] 2017-10-08 06:28
Seeing this right now too.  Is this fixable?

**Comment by spencerthayer** [comment] 2017-11-22 17:48
It's possible Soundcloud and Bandcamp have gotten wise.

**Comment by Lanchon** [comment] 2018-03-27 16:19
duplicate of #203, please close

**Comment by SimplicityGuy** [comment] 2020-08-02 03:05
Closing per previous comment.

**Closed by SimplicityGuy** 2020-08-02 03:05 UTC
