### ISSUE TITLE
AttributeError: 'exceptions.UnicodeEncodeError' object has no attribute 'replace'

### ISSUE THREAD

**Issue by letuxs** [Miserlou/SoundScrape#200] opened 2017-11-11 04:35 UTC
Hello,
i'm try to download list from Soundcloud by type 
`soundscrape "URL"`
and after downloaded like 5 tracks i got this error 
`Problem downloading Dina Elwedidi - دينا الوديدى - سكون
Traceback (most recent call last):
  File "/usr/bin/soundscrape", line 9, in <module>
    load_entry_point('soundscrape==0.30.1', 'console_scripts', 'soundscrape')()
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 119, in main
    process_soundcloud(vargs)
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 292, in process_soundcloud
    id3_extras=id3_extras)
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 460, in download_tracks
    puts_safe(e)
  File "/usr/lib/python2.7/site-packages/soundscrape/soundscrape.py", line 1315, in puts_safe
    puts(text)
  File "/usr/lib/python2.7/site-packages/clint/textui/core.py", line 57, in puts
    s = tsplit(s, NEWLINES)
  File "/usr/lib/python2.7/site-packages/clint/utils.py", line 69, in tsplit
    string = string.replace(i, final_delimiter)
AttributeError: 'exceptions.UnicodeEncodeError' object has no attribute 'replace'
`
and download is stooped.

how to fix this issue or how to skip this track ?

**Comment by Lanchon** [comment] 2018-03-27 16:18
duplicate of #203, please close

**Comment by SimplicityGuy** [comment] 2020-08-02 03:05
Closing per previous message.

**Closed by SimplicityGuy** 2020-08-02 03:05 UTC
