### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by kyleshockey** [Miserlou/SoundScrape#92] opened 2016-06-23 09:25 UTC
`→ pip install soundscrape --upgrade`

yields

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/90/jxwnj89d3d51f9y514ry5lt80000gn/T/pip-build-AOzHtQ/mutagen/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/90/jxwnj89d3d51f9y514ry5lt80000gn/T/pip-yUkPCb-record/install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in /private/var/folders/90/jxwnj89d3d51f9y514ry5lt80000gn/T/pip-build-AOzHtQ/mutagen
```

It's not SoundScrape causing the error directly... thought I'd drop this here anyway, in case anyone has an insight.

**Comment by pydo** [comment] 2016-06-24 04:47
Have you tried installing it in a virtualenv?

**Comment by Miserlou** [comment] 2016-06-24 18:14
Cannot reproduce, inside or outside of venv.

What system/python version?

**Comment by Miserlou** [comment] 2016-06-25 20:11
Closing without ability to reproduce, will open if more info.

**Closed** 2016-06-25 20:11 UTC

**Comment by jamieduk** [comment] 2017-12-20 21:50
I get error

  File "soundcloud_dl.py", line 1, in <module>
    from .downloader import downloader
ValueError: Attempted relative import in non-package
